version: '3'
services:
  keycloak:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_VENDOR=postgres
      - DB_USER=c18_39_n_java_angular
      - DB_PASSWORD=Ej0Nm4ltamnFJVL9do7UDlKZdivvvpce
      - DB_URL=postgresql://dpg-cp4mmegcmk4c73emahkg-a.oregon-postgres.render.com/docspot
      - KEYCLOAK_USER_ADMIN=docspot.nocountry@gmail.com
      - KEYCLOAK_PASSWORD_ADMIN=admin
      - KEYCLOAK_REALM=docspot